### ISSUE TITLE
"unclosed transport" error from asyncio.sslproto

### ISSUE THREAD

**Issue by Dax74** [freiheit/discord_rss_bot#18]
On windows, I have this error every time discord-bot-rss try to add a rss link on Discord:
`C:\Users\my_name\AppData\Local\Programs\Python\Python35-32\lib\asyncio\sslproto.py:327 ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x04D1FAFO>
warning.warn(2unclosed transport %r" % self, ResourceWarning)`
(04D1FAFO changes every time the bot try to add a feed)

I have upgrade `asyncio` to the latest version but this issue still remains.

**Comment by freiheit** [comment]
This one could take some digging to figure out... Might actually be a bug with python on windows... That might just be a warning and not an error.

Could you please set `debug = 3` in your .ini file and paste the full output? That will help me understand exactly what spot it happens at. Might be as simple as needing to call an explicit close on an object.

Some links for my own reference:
- https://bugs.python.org/issue25272
- https://bugs.python.org/issue26226
- https://github.com/python/asyncio/blob/master/asyncio/sslproto.py

**Comment by freiheit** [comment]
I can't reproduce this... Need more info.
