### ISSUE TITLE
Empty pubDate in instragram feed causes TypeError.

### ISSUE THREAD

**Issue by Chiharuuu** [freiheit/discord_rss_bot#20]
Instagram feed using "tag" (http://widget.websta.me/rss/tag/taghere) works as a feed and displays posts in Discord channel but only with a high max_age as mentioned in #19 previously. 

With "user" feed (http://widget.websta.me/rss/n/usernamehere), it displays back TypeError and doesn't post anything.

Below is debug output:

`DEBUG:__main__:instagramtest:processing entries`
`DEBUG:__main__:instagramtest:item:processing this entry`
`DEBUG:__main__:instagramtest:item:checking database history for this item`
`INFO:__main__:instagramtest:item http://websta.me/p/1214601160999041871_329452045 $ unseen, processing:`
`ERROR:__main__:instagramtest:Unexpected error:`
`ERROR:__main__:(<class 'TypeError'>, TypeError('Tuple or struct_time argument r$ quired',), <traceback object at 0x7f3c364d6ec8>)`
`ERROR:__main__:instagramtest:giving up`

**Comment by freiheit** [comment]
The pubDate on the items in that feed are empty, like `<pubDate></pubDate>`.

I think the way the code is written, a defined but empty pubDate would cause this error. I'm pushing a fix to this in a second. Please do another `git pull` and try it out.

**Comment by Chiharuuu** [comment]
This works and posts the links correctly, however due to that empty pubDate it grabs posts a lot older than the max_age if using the websta.me feed. It'll be fine once it's already grabbed them, though.

I've now set it up to read the instagram feed from my site (http://taedork.tk/instarss?username=user) and it works fine.

**Comment by freiheit** [comment]
Glad to hear this fixed that issue...

Since the individual items in that feed don't have a date, there's no way for max_age to actually work on that feed. (I consider it a bug in that feed)

It should be possible to add a feature to limit how many new items it will post when it processes a feed. I've put that enhancement in as Issue #21.
