### ISSUE TITLE
bot not running

### ISSUE THREAD

**Issue by tehface** [freiheit/discord_rss_bot#29]
set right token.. time zone etc etc

here's the windows cmd window

C:\Program Files\Python35\lib\site-packages\discord\__init__.py:47: UserWarning:
The next major version of discord.py (v0.10.0) will have major breaking changes
that will require updating/changing your code.
Please check the migrating guide to alleviate yourself of unexpected issues.
http://discordpy.readthedocs.org/en/latest/migrating.html
It is strongly recommended to make the switch as soon as possible.

  warnings.warn(_warning_message, UserWarning)
Traceback (most recent call last):
  File "feed2discord.py", line 490, in <module>
    @client.async_event
  File "C:\Program Files\Python35\lib\site-packages\discord\client.py", line 523, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.client.Client'>' object has no attribute 'async_event'
C:\Program Files\Python35\lib\site-packages\aiohttp\client.py:86: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x000001DCFF8DC278>
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DCFF8DC278>
C:\Program Files\Python35\lib\asyncio\base_events.py:379: ResourceWarning: unclosed event loop <_WindowsSelectorEventLoop running=False closed=False debug=False>

C:\Users\sirfacealot\Documents\discord_rss_bot>

**Comment by tehface** [comment]
issue resolved removed discord.py ( the requirements version ) and simply installed discord.py (ver 11 or something )

**Comment by eeisenhart** [comment]
Thanks for the report.

I've changed requirements.txt to `>=` and a more recent version, rather than the older version I was running, so hopefully nobody else will run into the problem you did...
